### ISSUE TITLE
Show random images in the demos 

### ISSUE THREAD

**Issue by aarongarciah** [alexjoverm/v-lazy-image#3]
Using the Unsplash API (or another one) to show a random image every time the demo loads will ensure that the image is not cached and will be easier to notice the lazy loading of the image.

It can be used calling this url https://source.unsplash.com/random or that same url with the specific dimensions if you want https://source.unsplash.com/random/500x500.

**Comment by aarongarciah** [comment]
Ok, now I see that this makes no sense in the progressive demo since you are using a blurred placeholder. Sorry!

https://codesandbox.io/s/l4vxvmpqym

**Comment by alexjoverm** [comment]
Yeah, I needed a service which let you use the same image in a different size. Medium is the one I found. You can set the size in any image url by replacing `SIZE`:

`https://cdn-images-1.medium.com/max/SIZE/1*xjGrvQSXvj72W4zD6IWzfg.jpeg`

What we can do is to use a different image for any case of the https://codesandbox.io/s/9l3n6j5944 demo. What do you think?

**Comment by aarongarciah** [comment]
Seems nice 👍

**Comment by alexjoverm** [comment]
Since you're the owner of the demo, I think you should do it. Some images you can use:

 - https://cdn-images-1.medium.com/max/800/1*Uc2QFJLZhu8MQ9-UgupGRA.jpeg
 - https://cdn-images-1.medium.com/max/800/1*TeymfgOgswgMnEJeYoYsVg.jpeg
 - https://cdn-images-1.medium.com/max/800/1*CimXtSxVLsdmFqq2viRu5Q.jpeg
 - https://cdn-images-1.medium.com/max/2000/1*V0F0-8AH8oV1LUSCbQsX4w.png

For the placeholder, just change the `max/NUMBER` for something small like `max/40`.

**Comment by aarongarciah** [comment]
Done :)
