### ISSUE TITLE
Add Polyfill intersection-observer

### ISSUE THREAD

**Issue by muhammadridho** [alexjoverm/v-lazy-image#31]
Hi I have a problem when using this library when on a **Safari Browser**. Namely the problem of the absence of fire **observer-intersections** on safari. can you add it to this library?

**Comment by jengel3** [comment]
I think it would be better to handle adding the polyfill yourself - however I do think that the library should automatically if the browser supports `IntersectionObserver` or not because otherwise it will throw errors, especially when `observer.disconnect()` is called [here](https://github.com/alexjoverm/v-lazy-image/blob/e00f2d3686dcfafc8e1be4d1dd52be8eec50ac03/src/index.js#L57)

**Comment by alexjoverm** [comment]
Yes, it's better to handle the polyfill yourself. It wouldn't be a bad idea to have some checks in the library for sure.

**Comment by alexjoverm** [comment]
From 1.3.1, it will check for IntersectionObserver and throw an Error if it doesn't find it 🎉
